language: cpp

os:
  - linux

compiler:
  # - clang # disabled clang due to missing libc++
  - gcc

notifications:
 email:
   on_success: change
   on_failure: always

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - if [ "$CXX" = "g++" ]; then sudo apt-get install g++-4.9 libboost-dev qt4-qmake; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [[ -f /usr/bin/g++ ]]; then sudo rm /usr/bin/g++; fi
  - sudo ln /usr/bin/g++-4.9 /usr/bin/g++
  - wget http://sourceforge.net/projects/boost/files/boost/1.57.0/boost_1_57_0.tar.bz2
  - tar jxf boost_1_57_0.tar.bz2
  - cd boost_1_57_0
  - sed 's|if (!(\*first1 != \*first2))|if (*first1 != *first2)|g' -i boost/container/vector.hpp
  - ./bootstrap.sh
  - sudo ./bjam release install -d0 --with-chrono --with-container --prefix=/usr/local -j4
  - sudo ldconfig

install:
  - "cd $TRAVIS_BUILD_DIR/tests/base/qtcreator"
  - "qmake"

script:
  - "cd $TRAVIS_BUILD_DIR/tests/base/qtcreator"
  - "make"
  - "./yas-base-test"
